name: tests 
on: push 
jobs: 
  run_tests: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout the repository 
        uses: actions/checkout@v3 
      - name: List files in the repository
        run: ls -R
      - name: Set up JDK 19  
        uses: actions/setup-java@v3 
        with: 
          java-version: '19'
          distribution: 'zulu' # 使用 Zulu 发行版，也可以选择 'temurin'
      - name: Cache Maven packages 
        uses: actions/cache@v3
        with: 
          path: ~/.m2 
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }} 
          restore-keys: ${{ runner.os }}-m2 
      - name: Run tests with Maven 
        run: mvn -B test --file OSSDP-Lab4/pom.xml
